CREATE TABLE IF NOT EXISTS settings (key TEXT PRIMARY KEY, value TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS shops (
  id INTEGER PRIMARY KEY, name TEXT NOT NULL, phone TEXT NOT NULL UNIQUE,
  pin_hash TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1
);
CREATE TABLE IF NOT EXISTS products (
  id INTEGER PRIMARY KEY, name_en TEXT NOT NULL, name_ml TEXT NOT NULL DEFAULT '',
  price REAL NOT NULL DEFAULT 0, active INTEGER NOT NULL DEFAULT 1, sort INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS orders (
  shop_id INTEGER NOT NULL, product_id INTEGER NOT NULL, date TEXT NOT NULL,
  qty INTEGER NOT NULL, price REAL NOT NULL, updated_at TEXT NOT NULL,
  PRIMARY KEY (shop_id, product_id, date)
);
CREATE INDEX IF NOT EXISTS idx_orders_date ON orders(date);
CREATE TABLE IF NOT EXISTS holidays (date TEXT PRIMARY KEY, note TEXT NOT NULL DEFAULT '');
CREATE TABLE IF NOT EXISTS deliveries (
  shop_id INTEGER NOT NULL, date TEXT NOT NULL, delivered INTEGER NOT NULL DEFAULT 1,
  PRIMARY KEY (shop_id, date)
);
CREATE TABLE IF NOT EXISTS payments (
  id INTEGER PRIMARY KEY, shop_id INTEGER NOT NULL, date TEXT NOT NULL,
  amount REAL NOT NULL, note TEXT NOT NULL DEFAULT ''
);
CREATE TABLE IF NOT EXISTS notifications (
  id INTEGER PRIMARY KEY, ts TEXT NOT NULL, text TEXT NOT NULL, seen INTEGER NOT NULL DEFAULT 0
);
CREATE TABLE IF NOT EXISTS login_fails (key TEXT PRIMARY KEY, count INTEGER NOT NULL, t INTEGER NOT NULL);
